### ISSUE TITLE
Re- or dual-license under an MIT/permissive license

### ISSUE THREAD

**Issue by Freso** [jbaiter/beetfs#1]
Hello,

Upstream beets is under [an MIT license](https://github.com/beetbox/beets/blob/master/LICENSE) so if it's ever desired for upstream to include your plugin with the source, they can't do it as it is now. Any chance you could reconsider the license or possibly dual-license the code in case upstream ever wants to include (perhaps even just some of) the code?

(Note that when GNU lists the [MIT license as compatible with the GPL](https://www.gnu.org/licenses/license-list.en.html#Expat), it means that MIT licensed code can be included in GPL code - but GPL code has additional limitations that means that GPL code cannot be included in MIT code.)

**Comment by jbaiter** [comment]
Unfortunately the code in the repository is not mine, I merely imported it from the now defunct http://code.google.com/p/beetfs by Martin Eve. You will have to reach out to him for a change of license.
